"""
Django settings for etipitaka_auth project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Production supplies DJANGO_SECRET_KEY via the environment; the literal
# below is an insecure placeholder for local development and CI only.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or 'django-insecure-dev-key-not-for-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '') == 'True'

FILE_SERVER = 'data.etipitaka.com'

ALLOWED_HOSTS = ['data.etipitaka.com', '128.199.181.198', 'localhost', '127.0.0.1', 'web']

# Trust the X-Forwarded-Proto header set by the reverse proxy to determine
# whether a request is secure (affects request.is_secure(), redirects, and
# oauth2_provider's registration_client_uri for dynamic client registration).
# Off by default: enable only when the front-most proxy unconditionally
# overwrites X-Forwarded-Proto (never passes through a client-supplied
# value) -- otherwise a client can spoof this header and trick Django into
# treating an insecure request as secure. Production opts in via its own
# compose override once that proxy behaviour is confirmed. Accepts the
# values an operator would plausibly write (see docs/remote-mcp-oauth-deploy.md).
TRUST_PROXY_PROTO = os.environ.get('TRUST_PROXY_PROTO', '').strip().lower() in ('1', 'true', 'yes')
if TRUST_PROXY_PROTO:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Once the proxy is confirmed to always set (never pass through a
    # client-supplied) X-Forwarded-Proto -- the precondition TRUST_PROXY_PROTO
    # itself gates on -- request.is_secure() is trustworthy, so it is also
    # safe to mark the session and CSRF cookies HTTPS-only and stop sending
    # them in the clear. It also makes the password-reset email link go out
    # as https://: PasswordResetView.form_valid passes
    # use_https=self.request.is_secure() to the form, so recovery.py's reset
    # link inherits this the same way. Off by default (bundled into this
    # same switch, not a separate env var) so the local http-only compose
    # stack keeps working: turned on over plain http, the browser would
    # never send these cookies back and login/CSRF would silently break.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'oauth2_provider',
    'user_data',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'etipitaka_auth.i18n.LanguageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
        'passkey': '20/min',
        # register_begin (its step-up password check) and password_remove
        # both accept a password guess whose payoff is persistent account
        # takeover -- an attacker passkey added there survives a password
        # change and isn't revoked by remove_password. Legitimate use is
        # one or two requests ever, so this sits well below 'passkey' and
        # applies alongside it, not instead of it. See PasskeyPasswordThrottle.
        'passkey_password': '5/min',
        # Desktop pairing polls every DESKTOP_POLL_INTERVAL seconds for up to
        # PASSKEY_DESKTOP_TTL, i.e. ~12 req/min for as long as one pairing is
        # open -- sustained traffic the one-shot 'passkey' ceremony budget was
        # never sized for. Anonymous requests key on client IP, so this has to
        # fit several machines sharing one public address (a temple or office
        # behind one NAT): 90/min carries about seven concurrently-pairing
        # clients. Pairing is a brief one-off act, not a steady state, so this
        # is generous in practice.
        'passkey_desktop': '90/min',
    },
    # nginx (nginx.conf) always appends the real client address as the LAST
    # entry of X-Forwarded-For via $proxy_add_x_forwarded_for -- it never
    # merely passes a client-supplied value through -- so DRF's throttle
    # should key on that last entry, not the whole header. Without this,
    # SimpleRateThrottle.get_ident falls back to using the entire raw
    # X-Forwarded-For string as the cache-key ident (api_settings.NUM_PROXIES
    # is None by default), and since a client can set that header to
    # anything on its *own* request, it can pick a fresh, never-seen ident on
    # every request and dodge the bucket entirely -- making every IP-keyed
    # DRF throttle in this project (LoginRateThrottle, PasskeyRateThrottle)
    # useless. NUM_PROXIES: 1 makes get_ident() take addrs[-1] instead: see
    # test_num_proxies_pins_ident_to_real_client_despite_spoofed_forwarded_for
    # in user_data/tests/test_passkey_views.py. This is 1 regardless of how
    # many real network hops sit in front of this container (in production a
    # host-level TLS terminator also sits ahead of nginx/ -- see
    # docs/remote-mcp-oauth-deploy.md): that host proxy is required to
    # *overwrite* X-Forwarded-For with just the client's address rather than
    # append to it, and this container's own nginx then resolves the real
    # peer through set_real_ip_from/real_ip_recursive before appending it via
    # $proxy_add_x_forwarded_for -- so the entry this container's nginx adds
    # is always the last one and always correct, no matter what a client (or
    # an untrusted earlier hop) put in front of it. NUM_PROXIES only needs to
    # change if this container's nginx stops being the sole thing appending
    # the header value Django ultimately trusts.
    'NUM_PROXIES': 1,
    # Maps a RecursionError from parsing a pathologically deep JSON body
    # (json.loads has no nesting-depth limit of its own) to a clean 400
    # instead of an unhandled 500; delegates every other exception to DRF's
    # own default handler. See user_data/drf_handlers.py.
    'EXCEPTION_HANDLER': 'user_data.drf_handlers.exception_handler',
}

# OAuth 2.1 Authorization Server (django-oauth-toolkit) backing the remote MCP
# endpoint. Clients self-register (DCR), must use PKCE, and receive the single
# read-only scope. Issuer is the site root so RFC 8414 discovery lives at
# /.well-known/oauth-authorization-server.
OAUTH_ISSUER_URL = os.environ.get('OAUTH_ISSUER_URL', 'https://data.etipitaka.com').rstrip('/')
# RFC 8707 audience of the remote MCP endpoint; must equal the MCP service's
# ETIPITAKA_RESOURCE_URL. See user_data.oauth_resource.
OAUTH_MCP_RESOURCE_URL = OAUTH_ISSUER_URL + '/mcp'

OAUTH2_PROVIDER = {
    'SCOPES': {
        'etipitaka:read': _('Read your E-Tipitaka bookmarks, highlights, tags, history and saved lexicon'),
    },
    'DEFAULT_SCOPES': ['etipitaka:read'],
    'PKCE_REQUIRED': True,
    'DCR_ENABLED': True,
    'DCR_REGISTRATION_PERMISSION_CLASSES': (
        'oauth2_provider.dcr.AllowAllDCRPermission',
    ),
    # https for web-callback clients (e.g. the Claude app); http is allowed
    # for any host so local/dev callbacks work (DOT has no loopback-only
    # mode). A client needing a custom scheme is onboarded by appending it
    # here. PKCE_REQUIRED, ROTATE_REFRESH_TOKEN and these schemes equal DOT's
    # defaults; pinned explicitly.
    'ALLOWED_REDIRECT_URI_SCHEMES': ['https', 'http'],
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 30 * 24 * 3600,
    'ROTATE_REFRESH_TOKEN': True,
    'RESOURCE_SERVER_TOKEN_RESOURCE_VALIDATOR': 'user_data.oauth_resource.validate_mcp_audience',
    # Every OAuth token write (issuance, refresh-token rotation, a
    # reuse-triggered family revoke, RFC 7009 revocation) takes a per-user
    # Postgres advisory lock before touching a row -- see
    # user_data.account_tokens.lock_user_tokens -- so it can never deadlock
    # against passkey recovery's own token revocation, which takes the same
    # lock.
    'OAUTH2_VALIDATOR_CLASS': 'user_data.oauth_validators.EtipitakaOAuth2Validator',
    # Enforce the OAuth 2.1 / RFC 9700 posture the server metadata advertises:
    # S256-only PKCE, no implicit/password grants, tokens only in headers,
    # RFC 9207 `iss` in the authorization response, and refresh-token reuse
    # detection (a replayed refresh token revokes the whole family).
    'REFRESH_TOKEN_REUSE_PROTECTION': True,
    'OIDC_ISS_ENDPOINT': OAUTH_ISSUER_URL,
    'COMPLIANT_BCP_RFC9700_PKCE_METHOD': True,
    'COMPLIANT_BCP_RFC9700_IMPLICIT_GRANT': True,
    'COMPLIANT_BCP_RFC9700_PASSWORD_GRANT': True,
    'COMPLIANT_BCP_RFC9700_ACCESS_TOKEN_TRANSPORT': True,
    'COMPLIANT_BCP_RFC9700_AUTHZ_RESPONSE_ISS': True,
    # What the RFC 8414 document (DOT's OAuthServerMetadataView, mounted at the
    # site root) advertises. `none` is for public DCR clients; the response/
    # grant lists name only the flows this server is meant to serve.
    # (client_credentials / device_code remain enabled inside DOT — restricting
    # them server-side is a recorded hardening follow-up.)
    'OAUTH2_TOKEN_ENDPOINT_AUTH_METHODS_SUPPORTED': ['none', 'client_secret_post',
                                                     'client_secret_basic'],
    'OAUTH2_RESPONSE_TYPES_SUPPORTED': ['code'],
    'OAUTH2_GRANT_TYPES_SUPPORTED': ['authorization_code', 'refresh_token'],
}

# Passkeys (WebAuthn). The relying-party ID and web origin default to the
# public issuer; local browser testing overrides both (localhost) through the
# gitignored docker-compose.override.yml, never the tracked .env. Android
# values are set the same way in production. See
# docs/superpowers/specs/2026-09-14-passkey-login-design.md.
def _env_list(name, default=''):
    # `or default` (not the dict-style get(name, default)) so an env var
    # explicitly set to '' -- e.g. a compose file overriding a value with an
    # empty string -- falls back to default instead of wiping it out.
    return [v.strip() for v in (os.environ.get(name) or default).split(',') if v.strip()]


PASSKEY_RP_ID = os.environ.get('PASSKEY_RP_ID', '').strip()
PASSKEY_WEB_ORIGIN = os.environ.get('PASSKEY_WEB_ORIGIN', '').strip()
PASSKEY_RP_NAME = 'E-Tipitaka'
PASSKEY_IOS_APP_IDS = _env_list('PASSKEY_IOS_APP_IDS', 'A6DJDJ7527.com.watnapp.E-Tipitaka-Plus')
PASSKEY_ANDROID_PACKAGE = os.environ.get('PASSKEY_ANDROID_PACKAGE', '')
PASSKEY_ANDROID_CERT_SHA256 = _env_list('PASSKEY_ANDROID_CERT_SHA256')
PASSKEY_CHALLENGE_TTL = 300  # seconds

# Desktop pairing handshakes live longer than a WebAuthn challenge: the window
# has to cover opening a browser, signing in to the website if there's no
# session yet, and then confirming the code.
PASSKEY_DESKTOP_TTL = 600  # seconds

# Declared explicitly, even though it matches Django's own default, because
# account_tokens.delete_user_sessions (passkey/password recovery signing out
# every other session) requires a plain, uncached 'db' session store it can
# read and delete rows from directly -- see check_session_engine and
# user_data.checks.check_passkey_session_engine, which fails `manage.py
# check` loudly if this ever drifts, instead of a silent 500 at recovery
# time. Pin here rather than relying on the default staying what it is.
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

ROOT_URLCONF = 'etipitaka_auth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'etipitaka_auth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'th'

LANGUAGES = [
    ('th', 'ไทย'),
    ('en', 'English'),
]

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

DEFAULT_FROM_EMAIL = 'E-Tipitaka Administrator'

# Console backend by default — verification emails print to the container log.
# Production overrides this with an SMTP backend via deployment config.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Email verification (DRF-native rebuild)
EMAIL_VERIFICATION_SALT = 'user-data.email-verify'
EMAIL_VERIFICATION_MAX_AGE = 60 * 60 * 24 * 3  # 3 days
EMAIL_VERIFICATION_URL = '/account/confirm-email/'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "assets"),
)

STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Directory holding the read-only canon edition/dictionary SQLite files that
# back the public /api/canon/* endpoints. In production set CANON_RESOURCES_DIR
# to the mount holding the rsync'd resources (e.g. /canon); when unset it falls
# back to media/canon, which the golden seed and local dev populate.
CANON_RESOURCES_DIR = os.environ.get('CANON_RESOURCES_DIR') or os.path.join(MEDIA_ROOT, 'canon')

try:
    from .local_settings import *
except ImportError:
    pass

import sys
if 'pytest' in sys.modules or 'test' in sys.argv:
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
    # Disable login throttling under tests — the in-process throttle cache
    # would otherwise accumulate across test cases and trip false 429s.
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES']['login'] = None
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES']['passkey'] = None
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES']['passkey_password'] = None
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES']['passkey_desktop'] = None
