"""
Django settings for etipitaka_auth project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Production supplies DJANGO_SECRET_KEY via the environment; the literal
# below is an insecure placeholder for local development and CI only.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or 'django-insecure-dev-key-not-for-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '') == 'True'

FILE_SERVER = 'data.etipitaka.com'

ALLOWED_HOSTS = ['data.etipitaka.com', '128.199.181.198', 'localhost', '127.0.0.1', 'web']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'oauth2_provider',
    'user_data',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'etipitaka_auth.i18n.LanguageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
    },
}

# OAuth 2.1 Authorization Server (django-oauth-toolkit) backing the remote MCP
# endpoint. Clients self-register (DCR), must use PKCE, and receive the single
# read-only scope. Issuer is the site root so RFC 8414 discovery lives at
# /.well-known/oauth-authorization-server.
OAUTH_ISSUER_URL = os.environ.get('OAUTH_ISSUER_URL', 'https://data.etipitaka.com').rstrip('/')

OAUTH2_PROVIDER = {
    'SCOPES': {
        'etipitaka:read': _('Read your E-Tipitaka bookmarks, highlights, tags, history and saved lexicon'),
    },
    'DEFAULT_SCOPES': ['etipitaka:read'],
    'PKCE_REQUIRED': True,
    'DCR_ENABLED': True,
    'DCR_REGISTRATION_PERMISSION_CLASSES': (
        'oauth2_provider.dcr.AllowAllDCRPermission',
    ),
    # https for web-callback clients (e.g. the Claude app); http is allowed
    # for any host so local/dev callbacks work (DOT has no loopback-only
    # mode). A client needing a custom scheme is onboarded by appending it
    # here. PKCE_REQUIRED, ROTATE_REFRESH_TOKEN and these schemes equal DOT's
    # defaults; pinned explicitly.
    'ALLOWED_REDIRECT_URI_SCHEMES': ['https', 'http'],
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 30 * 24 * 3600,
    'ROTATE_REFRESH_TOKEN': True,
    # Enforce the OAuth 2.1 / RFC 9700 posture the server metadata advertises:
    # S256-only PKCE, no implicit/password grants, tokens only in headers,
    # RFC 9207 `iss` in the authorization response, and refresh-token reuse
    # detection (a replayed refresh token revokes the whole family).
    'REFRESH_TOKEN_REUSE_PROTECTION': True,
    'OIDC_ISS_ENDPOINT': OAUTH_ISSUER_URL,
    'COMPLIANT_BCP_RFC9700_PKCE_METHOD': True,
    'COMPLIANT_BCP_RFC9700_IMPLICIT_GRANT': True,
    'COMPLIANT_BCP_RFC9700_PASSWORD_GRANT': True,
    'COMPLIANT_BCP_RFC9700_ACCESS_TOKEN_TRANSPORT': True,
    'COMPLIANT_BCP_RFC9700_AUTHZ_RESPONSE_ISS': True,
    # What the RFC 8414 document (DOT's OAuthServerMetadataView, mounted at the
    # site root) advertises. `none` is for public DCR clients; the response/
    # grant lists name only the flows this server is meant to serve.
    # (client_credentials / device_code remain enabled inside DOT — restricting
    # them server-side is a recorded hardening follow-up.)
    'OAUTH2_TOKEN_ENDPOINT_AUTH_METHODS_SUPPORTED': ['none', 'client_secret_post',
                                                     'client_secret_basic'],
    'OAUTH2_RESPONSE_TYPES_SUPPORTED': ['code'],
    'OAUTH2_GRANT_TYPES_SUPPORTED': ['authorization_code', 'refresh_token'],
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

ROOT_URLCONF = 'etipitaka_auth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'etipitaka_auth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'th'

LANGUAGES = [
    ('th', 'ไทย'),
    ('en', 'English'),
]

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

DEFAULT_FROM_EMAIL = 'E-Tipitaka Administrator'

# Console backend by default — verification emails print to the container log.
# Production overrides this with an SMTP backend via deployment config.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Email verification (DRF-native rebuild)
EMAIL_VERIFICATION_SALT = 'user-data.email-verify'
EMAIL_VERIFICATION_MAX_AGE = 60 * 60 * 24 * 3  # 3 days
EMAIL_VERIFICATION_URL = '/account/confirm-email/'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "assets"),
)

STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Directory holding the read-only canon edition/dictionary SQLite files that
# back the public /api/canon/* endpoints. In production set CANON_RESOURCES_DIR
# to the mount holding the rsync'd resources (e.g. /canon); when unset it falls
# back to media/canon, which the golden seed and local dev populate.
CANON_RESOURCES_DIR = os.environ.get('CANON_RESOURCES_DIR') or os.path.join(MEDIA_ROOT, 'canon')

try:
    from .local_settings import *
except ImportError:
    pass

import sys
if 'pytest' in sys.modules or 'test' in sys.argv:
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
    # Disable login throttling under tests — the in-process throttle cache
    # would otherwise accumulate across test cases and trip false 429s.
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES']['login'] = None
