# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
