# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_data.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_data', '0002_userdata_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('checksum', models.TextField(blank=True, null=True)),
                ('platform', models.TextField()),
                ('file', models.FileField(upload_to=user_data.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
